platform :ios, '9.0'

target 'FoodTinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTinder
    pod 'SwiftyJSON'
    pod 'Alamofire'
end
